### PR TITLE
chore(storybook): prioritize Connected stories over Static

### PR DESCRIPTION
**Pull request by sashathor**
## Description of changes

This PR solves [The main examples should use the connected mode](https://linear.app/propel/issue/PRO-2402/the-main-examples-should-use-the-connected-mode)

## Checklist

Before merging to main:

- [ ] Tests
- [ ] Manually tested in React apps
- [x] Release notes
- [x] Approved

## Release notes
# App changes

## Storybook

- Prioritized Connected stories over Static 
```

### CODE REVIEW

**Comment by acossta** [comment]
Playing around with it here: https://ui-kit-git-sasha-pro-2402the-main-examples-sh-7255da-propeldata.vercel.app/

Overall, it looks good. A couple of things:
- The usage section seems to be broken (screenshot)

Screenshot 2023-09-22 at 9 25 56 AM

- The connected components sometimes work, sometimes don't. I'm getting a lot of authentication errors.

Screenshot 2023-09-22 at 9 27 17 AM

**Comment by sashathor** [comment]
> Playing around with it here: https://ui-kit-git-sasha-pro-2402the-main-examples-sh-7255da-propeldata.vercel.app/
> 
> Overall, it looks good. A couple of things:
> 
> * The usage section seems to be broken (screenshot)
> 
> Screenshot 2023-09-22 at 9 25 56 AM

That's a good catch, thank you @acossta! Fixed!

> 
> * The connected components sometimes work, sometimes don't. I'm getting a lot of authentication errors.
> 
> Screenshot 2023-09-22 at 9 27 17 AM

I've added a README to Storybook package folder with a note about the local development. Briefly, Vercel handles serverless functions. To handle it locally, we need to run a server (we can introduce this feature later). Currently, we can avoid this step by providing an access token via the env variable.

**Comment by acossta** [comment]
> I've added a README to Storybook package folder with a note about the local development. Briefly, Vercel handles serverless functions. To handle it locally, we need to run a server (we can introduce this feature later). Currently, we can avoid this step by providing an access token via the env variable.

I run into this not in local development but testing it on this URL: https://ui-kit-git-sasha-pro-2402the-main-examples-sh-7255da-propeldata.vercel.app/

**Comment by sashathor** [comment]
> > I've added a README to Storybook package folder with a note about the local development. Briefly, Vercel handles serverless functions. To handle it locally, we need to run a server (we can introduce this feature later). Currently, we can avoid this step by providing an access token via the env variable.
> 
> I run into this not in local development but testing it on this URL: https://ui-kit-git-sasha-pro-2402the-main-examples-sh-7255da-propeldata.vercel.app/

Got it! Thank you for pointing out. The behavior was caused by one particular story that had a wrong `render` setting. Fixed: https://ui-2aqo4lesk-propeldata.vercel.app/?path=%2Fdocs%2Fcomponents-counter--overview

**Review by markandrus — APPROVED** [review]
LGTM

**Comment by acossta** [comment]
Looks good. Just one thing. In the "Usage" section the Connected mode seems to be duplicated.

Screenshot 2023-09-28 at 7 57 25 AM

**Comment by sashathor** [comment]
> fix(storybook): remove duplicate of Connected mode section in Usage

Yeah, it was fixed in
image

**Pull request merged**
